version: '3.7'
services:
  ingress:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/staging.poridhi.io/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/staging.poridhi.io/privkey.pem:/etc/nginx/privkey.pem
    ports:
      - 80:80
      - 443:443
  portal:
    image: poridhi/frontend:v5.0
  admin:
    image: poridhi/admin_frontend:0.2.0