version: '3.7'
services:
  ingress:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./poridhi-ss.crt:/etc/nginx/poridhi-ss.crt
      - ./poridhi-ss.key:/etc/nginx/poridhi-ss.key
    ports:
      - 80:80
      - 443:443
  portal:
    image: poridhi/frontend:v5.0
  admin:
    image: poridhi/admin_frontend:0.2.0